### ISSUE TITLE
will not load, GTK conflict issue

### ISSUE THREAD

**Issue by stevebowser** [mohan43u/gistnotes#13]
Hi, when I try to load gistbin, exactly per your README and some other hacks i tried, i always get the following when attempted from a command line, and no response when i try anything in the GUI:

Requiring namespace 'Gtk' version '2.0', but '3.0' is already loaded

I'm running OpenSuse Tumbleweed, Gnome 3.20.2, all fully updated as of 7/11/16.  Kernel:  linux-thpu 4.6.3-1-default

Sounds like a great app though!  Let me know if you need anymore info.

Thanks,

Steve

**Comment by mohan43u** [comment]
hi, thanks for your time, I checked the latest gistnotes in fedora24 and Arch with 3.20.2. It works without any issue. your issue seems specific to opensuse in girepository importer.

http://lists.opensuse.org/opensuse-bugs/2014-10/msg02616.html

Resolution steps:
1. check if you see "Gtk-2.0.typelib" as well as "Gtk-3.0.typelib" in /usr/lib/girepository-2.0 if you dont see "Gtk-3.0.typelib", please try to bring it to your OS by installing relevent package in opensuse
2. if you see both typelib files and you still get this issue. then open ~/.local/share/gnome-shell/extensions/gistnotes@mohan43u.gmail.com/ui.js in a text editor and put this line before the first non-comment line

`imports.gi.versions.Gtk = "3.0"`

I hope this should fix the issue your are facing. Usually, girepository importer should import whatever latest version of Gtk available in your system (atleast that how Fedora and Arch works). I'm not sure if the developer need to import the specific version of Gtk instead of telling the importer to import the latest version automatically.
