### ISSUE TITLE
Ugly Error 

### ISSUE THREAD

**Issue by mdrmike** [mohan43u/gistnotes#3]
Great extension... love the idea!  However I did run into a problem.  I'm not sure how important this is in the scheme of the project, but thought I'd share.
### Background

First use after installation, and _lost a network connection_ without realizing, clicked on the indicator icon, then was presented with this Ugly error.  It was not clear at first that it was from the **gistnotes extension**, as I had installed multiple extensions and was unfamiliar with the icon.  As a result, the message is missing clear information, but probably ok for the average github user.

![screenshot from 2015-01-05 16 59 47](https://cloud.githubusercontent.com/assets/259940/5622726/c5b8f546-94fc-11e4-8f25-1a5db898772d.png)

**Comment by mohan43u** [comment]
at present, the app don't handle any errors which occur during authorization, it only listens for redirect signals and rest of the authorization handled by webkitgtk (which throws the error you mentioned). I feel that its not necessary to handle all the errors which can occur during authorization because webkitgtk will show it to the user anyway (but, those error messages may not be well explained).

**Comment by mohan43u** [comment]
I'll keep this issue open till you accept my explanation or I'll get time to handle all the webkit errors.

**Comment by mdrmike** [comment]
:+1:  I mostly wanted to make sure you were aware of the error condition, and totally understandable the approach.  

As a side: I'd have been fine if you closed, or closed with a comment you could reopen; working issue queues for free can become tedious.
